version: "2"
services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/web:/usr/share/nginx/html
    ports:
      - "80:80"
    links:
      - php:php

  php:
    build: ./php
    restart: always
    expose:
      - "9000"
    links:
      - mysql
      - redis
    volumes:
      - ./www/web:/usr/share/nginx/html

  mysql:
    build: ./mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
 
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
